config/routes.rb
Rails.application.routes.draw do
  get "intip_workspaces/index"
  get "workspaces/index"

  # devise routes
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  # rails admin routes
  mount RailsAdmin::Engine => "/secretroom", as: "rails_admin"

  root "homepages#index"
  get "privacy-policy", to: "homepages#privacy_policy"
  get "carts", to: "carts#index"
  get "/hello", to: "homepages#hello"
  get "/pdf", to: "homepages#generatepdf"
  get "/table-data/session/set", to: "application#submission_set"

  #======------ SETTINGS ------======#
  post "/settings/update", to: "super_admins#update_settings"

  #======------ DASHBOARDS ------======#
  get "/dashboards", to: "dashboards#index"
  get "/dashboards/counter", to: "dashboards#counter"
  get "/dashboards/profile", to: "dashboards#profile"
  post "/dashboards/profile/update", to: "dashboards#update_profile"
  post "/dashboards/password/update", to: "dashboards#update_password"

  #======------ SUPER ADMIN ------======#
  get "/superadmin", to: "super_admins#index"
  get "/superadmin/member", to: "super_admins#list_member"
  get "/superadmin/member/edit/:id", to: "super_admins#edit_member", as: "sa_edit_member"
  post "/superadmin/member/edit/process", to: "super_admins#process_update_member"
  get "/superadmin/member/new", to: "super_admins#new_member", as: "sa_new_member"
  post "/superadmin/member/new/process", to: "super_admins#process_create_member"
  delete "/superadmin/member/delete/all", to: "super_admins#destroy_all_member", as: "sa_destroy_all_member"
  delete "/superadmin/member/delete/:id", to: "super_admins#destroy_member", as: "sa_destroy_member"
  get "/superadmin/admin", to: "super_admins#list_admin"
  get "/superadmin/admin/edit/:id", to: "super_admins#edit_admin", as: "sa_edit_admin"
  post "/superadmin/admin/edit/process", to: "super_admins#process_update_admin"
  get "/superadmin/admin/new", to: "super_admins#new_admin", as: "sa_new_admin"
  post "/superadmin/admin/new/process", to: "super_admins#process_create_admin"
  delete "/superadmin/admin/delete/:id", to: "super_admins#destroy_admin", as: "sa_destroy_admin"
  get "/superadmin/validasi", to: "super_admins#validations"
  get "/superadmin/validasi/:id", to: "super_admins#validation_detail", as: "sa_validation_detail"
  get "/superadmin/pola-ruang", to: "super_admins#space_patterns"
  get "/superadmin/pola-ruang/:id", to: "super_admins#space_pattern_detail", as: "sa_space_pattern_detail"
  get "/superadmin/settings", to: "super_admins#settings"

  #======------ MEMBER VALIDASI ------======#
  get "/dashboards/member", to: "members#index"
  get "/dashboards/member/validasi", to: "members#validation"
  get "/dashboards/member/validasi/submission", to: "members#validation_submission"
  post "/dashboards/member/validasi/submission", to: "members#validation_process_submission"
  get "/dashboards/member/pola-ruang", to: "members#space_pattern"
  get "/dashboards/member/pola-ruang/submission", to: "members#space_pattern_submission"
  post "/dashboards/member/pola-ruang/submission", to: "members#space_pattern_process_submission"
  get "/dashboards/member/submission/edit/:id", to: "members#submission_edit", as: "member_submission_edit"
  get "/dashboards/member/submission/detail/:id", to: "members#submission_detail", as: "member_submission_detail"
  put "/dashboards/member/submission/detail/:id", to: "members#prosess_submission_edit", as: "member_process_submission_edit"

  #======------ ADMIN VALIDASI ------======#
  get "/dashboards/admin", to: "admins#index"
  get "/dashboards/admin/permohonan", to: "admins#applications"
  get "/dashboards/admin/permohonan/session/set", to: "admins#submission_set"
  get "/dashboards/admin/permohonan/session/approve", to: "admins#submission_approve"
  delete "/dashboards/admin/permohonan/session/delete", to: "admins#submission_delete"
  get "/dashboards/admin/permohonan/loket", to: "admins#counter"
  get "/dashboards/admin/permohonan/loket/ambil/:id", to: "admins#taken_submission", as: "admin_taken_submission"
  post "/dashboards/admin/permohonan/loket/ambil/process", to: "admins#process_taken_submission", as: "admin_process_taken_submission"
  get "/dashboards/admin/permohonan/revisi", to: "admins#revisions"
  get "/dashboards/admin/permohonan/revisi/member/:id", to: "admins#member_revisions", as: "admin_member_revision"
  post "/dashboards/admin/permohonan/revisi/member/process", to: "admins#process_member_revision", as: "admin_process_member_revision"
  get "/dashboards/admin/permohonan/setujui/:id", to: "admins#accept_submission", as: "admin_accept_submission"
  post "/dashboards/admin/permohonan/setujui/process", to: "admins#process_accept_submission", as: "admin_process_accept_submission"
  get "/dashboards/admin/permohonan/detail/:id", to: "admins#detail_submission", as: "admin_detail_submission"
  delete "/dashboards/admin/permohonan/delete/:id", to: "admins#delete_submission", as: "admin_delete_submission"

  #======------ KASUBSI ------======#
  get "/dashboards/kasubsi", to: "kasubsis#index"
  get "/dashboards/kasubsi/accept/:id", to: "kasubsis#accept_submission", as: "kasubsi_accept_submission"
  get "/dashboards/kasubsi/permohonan", to: "kasubsis#application_report"
  get "/dashboards/kasubsi/permohonan/detail/:id", to: "kasubsis#submission_detail", as: "kasubsi_detail_submission"
  get "/dashboards/kasubsi/permohonan/session/approve", to: "kasubsis#submission_approve"

  #======------ ADMIN INTIP ------======#
  get "intip/admin", to: "intips#index"
  get "intip/admin/members", to: "intips#members"
  get "intip/admin/members/new", to: "intips#new_member"
  post "intip/admin/members/create", to: "intips#create_member"
  get "intip/admin/members/edit/:id", to: "intips#edit_member", as: "intip_admin_members_edit"
  get "intip/admin/members/detail/:id", to: "intips#detail_member", as: "intip_admin_members_detail"
  delete "intip/admin/members/delete/:id", to: "intips#delete_member", as: "intip_admin_members_delete"
  put "intip/admin/members/edit/process/:id", to: "intips#process_edit_member", as: "intip_admin_members_edit_process"
  get "intip/admin/permohonan", to: "intips#submissions"
  get "intip/admin/intip/members", to: "intips#intip_members"
  get "intip/admin/intip/members/:id", to: "intips#intip_members_detail", as: "intip_admin_intip_members_detail"
  get "intip/admin/intip/members/:id/permohonan/:workspace_id", to: "intips#intip_members_permohonan", as: "intip_admin_intip_members_permohonan"

  #======------ GPS ADMIN ------======#
  get "gps/admin", to: "gps#index"
  get "gps/admin/gps/members", to: "gps#gps_members"
  get "gps/admin/gps/members/:id", to: "gps#gps_members_detail", as: "gps_admin_gps_members_detail"
  delete "gps/admin/gps/members/:id/delete/workspace/:workspace_id", to: "gps#delete_workspace_member", as: "gps_admin_gps_members_delete_workspace"
  get "gps/admin/gps/members/:id/permohonan/:workspace_id", to: "gps#gps_members_permohonan", as: "gps_admin_gps_members_permohonan"

  get "gps/admin/permohonan/:id", to: "gps#detail", as: "gps_admin_permohonan_detail"

  get "gps/admin/members", to: "gps#members"
  get "gps/admin/members/new", to: "gps#new_member"
  post "gps/admin/members/create", to: "gps#create_member"
  get "gps/admin/members/edit/:id", to: "gps#edit_member", as: "gps_admin_members_edit"
  get "gps/admin/members/detail/:id", to: "gps#detail_member", as: "gps_admin_members_detail"
  delete "gps/admin/members/delete/:id", to: "gps#delete_member", as: "gps_admin_members_delete"
  put "gps/admin/members/edit/process/:id", to: "gps#process_edit_member", as: "gps_admin_members_edit_process"

  #======------ MEMBER INTIP ------======#
  get "intip/member", to: "member_intips#index"
  get "intip/member/permohonan", to: "member_intips#intip"
  get "intip/member/permohonan/detail/:id", to: "member_intips#show", as: "intips_member_permohonan_detail"
  post "intip/member/permohonan/action", to: "member_intips#action"
  get "intip/member/permohonan/new", to: "member_intips#new_intip_submission"
  get "intip/member/permohonan/download", to: "member_intips#intip_submission"
  post "intip/member/permohonan/submit", to: "member_intips#submit_intip_submission"
  post "intip/member/permohonan/process-data", to: "member_intips#process_data"
  get "intips/workspaces", to: "intip_workspaces#index"
  post "intips/workspaces", to: "intip_workspaces#process_create"
  get "intips/workspaces/create", to: "intip_workspaces#create"
  get "intips/workspaces/detail/:id", to: "intip_workspaces#detail", as: "intips_member_workspaces_detail"
  delete "intips/workspaces/delete/:id", to: "intip_workspaces#delete", as: "intips_member_workspaces_delete"
  get "intips/workspaces/:id", to: "intip_workspaces#show", as: "intips_member_workspaces_show"
  get "intips/workspaces/:id/buat-permohonan", to: "intip_workspaces#new_submission", as: "intips_member_workspaces_new_submission"
  post "intips/workspaces/:id/buat-permohonan/process", to: "intip_workspaces#process_new_submission", as: "intips_member_workspaces_process_new_submission"
  post "intips/workspaces/permohonan/process-data", to: "intip_workspaces#process_data", as: "intips_member_workspaces_permohonan_process_data"

  #======------ GPS MEMBER ------======#
  get "gps/member", to: "member_gps#index"
  get "gps/member/permohonan", to: "member_gps#gps"
  get "gps/member/permohonan/new", to: "member_gps#new_gps_submission"
  post "gps/member/permohonan/submit", to: "member_gps#submit_gps_submission"
  delete "gps/member/permohonan/delete", to: "member_gps#delete_gps_submission"
  put "gps/member/permohonan/sent", to: "member_gps#sent_gps_submission"
  get "gps/member/permohonan/:id", to: "member_gps#detail_gps_submission", as: "gps_member_permohonan_detail"
  get "gps/member/permohonan/edit/:id", to: "member_gps#edit_gps_submission", as: "gps_member_permohonan_edit"

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipients, foreign_key: 'recipient_id', class_name: 'Notification'
  has_many :actors, foreign_key: 'actor_id', class_name: 'Notification'
  has_many :notifications, foreign_key: :recipient_id
  has_one :user_detail, dependent: :destroy
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :submissions, dependent: :destroy
  has_many :intips, dependent: :destroy
  has_many :gps_plottings, dependent: :destroy
  has_many :workspaces, dependent: :destroy
  has_many :working_areas, dependent: :destroy

  validates :username, uniqueness: true
  validates :email, uniqueness: true

  scope :members, -> { joins(:roles).where('roles.name ILIKE ?', '%member%') }
  scope :admins, -> { joins(:roles).where('roles.name ILIKE ? OR roles.name ILIKE ?', '%admin%', '%kasubsi%') }

  after_create :set_working_area_user

  # kaminari
  paginates_per 10

  def gps_with_workspace(workspace_id)
    return gps_plottings.where('sent_at IS NULL') unless workspace_id

    gps_plottings.where('sent_at IS NULL AND workspace_id = ?', workspace_id)
  end

  def set_working_area_user
    area = Area.find_by(is_default: true)
    WorkingArea.create(user_id: self.id, area_id: area.id)
  rescue
    Rails.logger.info '======> ERROR SET WORKING AREA <======'
  end

  def intips_today
    intips.where(created_at: Date.today)
  end

  def gps_plottings_today
    gps_plottings.where(created_at: Date.today)
  end

  def self.process_api_login(user)
    current_user = find_by(username: user['username'].to_s.downcase)
    auth         = current_user.present? && current_user.valid_password?(user['password'])
    confirmed    = current_user.confirmed_at.present? rescue false

    return { status: 'FAILED', errors: ['Failed to login'] } unless (current_user.present? && auth )
    return { status: 'FAILED', errors: ['You have to confirm your email address before continuing.'] } unless confirmed

    area = current_user.working_areas.first.area rescue nil
    token = get_auth_token(current_user.id)
    unless area.nil?
      { status: 'SUCCESS', results: { token: "Bearer #{token}", working_area_name: area.name, working_area_id: area.area_id } }
    else
      { status: 'SUCCESS', results: { token: "Bearer #{token}", working_area_name: '', working_area_id: '' } }
    end
  end

  def self.process_api_register(user)
    new_user = new(username: user['username'], password: user['password'], email: user['email'])
    return { status: 'FAILED', errors: new_user.errors.full_messages } unless new_user.save

    
    UserDetail.create(fullname: user['fullname'], id_number: user['id_number'], user_id: new_user.id)
    UserRole.find_or_create_by(user_id: new_user.id, role_id: Role.member_sipilot_id) # set default user register has member role

    { status: 'SUCCESS', results: { message: 'You will receive an email with instructions for how to confirm your email address in a few minutes.' } }
  end

  def self.get_auth_token(user_id)
    Auth.issue({ user: user_id })
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def my_notifications
    Notification.where('recipient_id = ? AND read_at IS NULL', id).order('created_at desc').uniq { |val| val.notifiable_id }
  end

  def self.member_intip
    joins(:user_roles, :roles).where('roles.name ILIKE ?', "%member intip%")
  end

  def self.member_gps
    joins(:user_roles, :roles).where('roles.name ILIKE ?', "%member gps%")
  end

  def member_sipilot_id
    Role.where('name ILIKE ?', "%member sipilot%").first.try(:id)
  end

  def admin_validasi?
    roles.where('name ILIKE ?', '%admin validasi%').present?
  end

  def admin_tematik?
    roles.where('name ILIKE ?', '%admin tematik%').present?
  end

  def admin_buku_tanah?
    roles.where('name ILIKE ?', '%admin buku tanah%').present?
  end

  def admin_pola_ruang?
    roles.where('name ILIKE ?', '%admin pola ruang%').present?
  end

  def member_sipilot?
    roles.where('name ILIKE ?', '%member sipilot%').present?
  end

  def admin_intip?
    roles.where('name ILIKE ?', '%admin intip%').present?
  end

  def member_intip?
    roles.where('name ILIKE ?', '%member intip%').present?
  end

  def admin_gps?
    roles.where('name ILIKE ?', '%admin gps%').present?
  end

  def member_gps?
    roles.where('name ILIKE ?', '%member gps%').present?
  end

  def kasubsi_tematik?
    roles.where('name ILIKE ?', '%kasubsi tematik%').present?
  end

  def kasubsi_pola_ruang?
    roles.where('name ILIKE ?', '%kasubsi pola ruang%').present?
  end

  def kasubsi_pendaftaran?
    roles.where('name ILIKE ?', '%kasubsi pendaftaran%').present?
  end

  def super_admin?
    roles.where('name ILIKE ?', '%super admin%').present?
  end

  def role_name
    roles.first.name
  rescue StandardError
    ''
  end

  def role_id
    roles.first.id
  rescue StandardError
    ''
  end

  def fullname
    user_detail&.fullname
  end

  def id_number
    user_detail&.id_number
  end

  def address
    user_detail&.address
  end

  def phone_number
    user_detail&.phone_number
  end

  def profile_photo
    # Rails.application.routes.url_helpers.rails_blob_url(user_detail.profile_photo, only_path: true)
    user_detail.profile_photo
  rescue StandardError
    ''
  end
end

app/helpers/member_intips_helper.rb
module MemberIntipsHelper
end

app/views/member_intips/_table_search_n_action.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
      <!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
  <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
    <div class="ml-4 mt-2">

    <div>
      <%= search_form_for(@search, url: intip_member_permohonan_path, method: 'get') do |f| %>
      <div class="mt-1 flex rounded-md shadow-sm">
        <div class="relative flex items-stretch flex-grow focus-within:z-10">

        <%= f.select 'village_id_eq', options_from_collection_for_select(@villages, 'id', 'name', @village_id), include_blank: true %>

        <%#= f.text_field :fullname_cont, value: @name_params, class: "focus:ring-blue-500 focus:border-blue-500 block w-full rounded-none rounded-l-md sm:text-sm border-gray-300", placeholder: 'Cari Pendaftar' %>
        </div>
        <%= f.submit class: "-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500" do %>
        <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
        <% end %>
      </div>
      <% end %>
    </div>

    </div>
    <div class="ml-4 mt-2 flex-shrink-0">
      <%#= link_to 'Ajukan Intip', intip_member_permohonan_new_path, class: "relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    </div>
  </div>
</div>

app/views/member_intips/intip.html.erb
<%= render "shareds/table_title", name: 'INVENTARISASI TANAH INSTANSI PEMERINTAH' %>

<%= render 'member_intips/table_filter' %>

<%= render "member_intips/table_search_n_action" %>

  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8 py-1">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

        <%= form_tag intips_member_workspaces_permohonan_process_data_path, method: :post do %>
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  No
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'NUI', column: 'nui'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'NIB', column: 'nib'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Nama Instansi Pemerintah', column: 'name'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Kecamatan', column: 'sub_district_name'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Desa', column: 'village_name'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Alas Hak', column: 'hak_name'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Jenis Hak', column: 'hak_type'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Nomer Hak / Nomer Letter C', column: 'number_letter_c:'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Tanggal', column: 'date'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Jangka Waktu', column: 'time_range'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Penguasaan Tanah', column: 'land_control'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Peruntukan Tanah', column: 'land_allocation'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Penggunaan Tanah', column: 'land_use'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Pemanfaatan Tanah', column: 'land_utilization'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Luas (M2)', column: 'land_size'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Lat', column: 'lattitude'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Lng', column: 'longitude'%>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <%= render "member_intips/column_header", title: 'Keterangan', column: 'description'%>
                </th>
                <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Aksi
                </th>
              </tr>
            </thead>
            <tbody>
              <% @intips.each.with_index(1) do |intip, index|%>
                <tr class="bg-white">
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= check_box_tag "submission_ids[]", intip.id %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= index %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.nui %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.nib %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.name %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.sub_district_name %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.village_name %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.hak_number %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.hak_name %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.number_letter_c %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.date %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.time_range %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.land_control %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.land_allocation %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.land_use %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.land_utilization %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.land_size %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.lattitude %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.longitude %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= intip.description %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <%= render 'shareds/tables/button_edit', action_path: gps_member_permohonan_edit_path(intip.id) %>
                    <%= render 'shareds/tables/button_detail', action_path: intips_member_permohonan_detail_path(intip.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% if @intips.any? %>
            <div class="p-5">
              <%= submit_tag "Kirim", name: 'button',class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              <%= submit_tag "Hapus", name: 'button', class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  <%= render "member_intips/pagination", name: '' %>

</div>