config/routes.rb
Rails.application.routes.draw do
  get "intip_workspaces/index"
  get "workspaces/index"

  # devise routes
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  # rails admin routes
  mount RailsAdmin::Engine => "/secretroom", as: "rails_admin"

  root "homepages#index"
  get "privacy-policy", to: "homepages#privacy_policy"
  get "carts", to: "carts#index"
  get "/hello", to: "homepages#hello"
  get "/pdf", to: "homepages#generatepdf"
  get "/table-data/session/set", to: "application#submission_set"

  #======------ SETTINGS ------======#
  post "/settings/update", to: "super_admins#update_settings"

  #======------ DASHBOARDS ------======#
  get "/dashboards", to: "dashboards#index"
  get "/dashboards/counter", to: "dashboards#counter"
  get "/dashboards/profile", to: "dashboards#profile"
  post "/dashboards/profile/update", to: "dashboards#update_profile"
  post "/dashboards/password/update", to: "dashboards#update_password"

  #======------ SUPER ADMIN ------======#
  get "/superadmin", to: "super_admins#index"
  get "/superadmin/member", to: "super_admins#list_member"
  get "/superadmin/member/edit/:id", to: "super_admins#edit_member", as: "sa_edit_member"
  post "/superadmin/member/edit/process", to: "super_admins#process_update_member"
  get "/superadmin/member/new", to: "super_admins#new_member", as: "sa_new_member"
  post "/superadmin/member/new/process", to: "super_admins#process_create_member"
  delete "/superadmin/member/delete/all", to: "super_admins#destroy_all_member", as: "sa_destroy_all_member"
  delete "/superadmin/member/delete/:id", to: "super_admins#destroy_member", as: "sa_destroy_member"
  get "/superadmin/admin", to: "super_admins#list_admin"
  get "/superadmin/admin/edit/:id", to: "super_admins#edit_admin", as: "sa_edit_admin"
  post "/superadmin/admin/edit/process", to: "super_admins#process_update_admin"
  get "/superadmin/admin/new", to: "super_admins#new_admin", as: "sa_new_admin"
  post "/superadmin/admin/new/process", to: "super_admins#process_create_admin"
  delete "/superadmin/admin/delete/:id", to: "super_admins#destroy_admin", as: "sa_destroy_admin"
  get "/superadmin/validasi", to: "super_admins#validations"
  get "/superadmin/validasi/:id", to: "super_admins#validation_detail", as: "sa_validation_detail"
  get "/superadmin/pola-ruang", to: "super_admins#space_patterns"
  get "/superadmin/pola-ruang/:id", to: "super_admins#space_pattern_detail", as: "sa_space_pattern_detail"
  get "/superadmin/settings", to: "super_admins#settings"

  #======------ MEMBER VALIDASI ------======#
  get "/dashboards/member", to: "members#index"
  get "/dashboards/member/validasi", to: "members#validation"
  get "/dashboards/member/validasi/submission", to: "members#validation_submission"
  post "/dashboards/member/validasi/submission", to: "members#validation_process_submission"
  get "/dashboards/member/pola-ruang", to: "members#space_pattern"
  get "/dashboards/member/pola-ruang/submission", to: "members#space_pattern_submission"
  post "/dashboards/member/pola-ruang/submission", to: "members#space_pattern_process_submission"
  get "/dashboards/member/submission/edit/:id", to: "members#submission_edit", as: "member_submission_edit"
  get "/dashboards/member/submission/detail/:id", to: "members#submission_detail", as: "member_submission_detail"
  put "/dashboards/member/submission/detail/:id", to: "members#prosess_submission_edit", as: "member_process_submission_edit"

  #======------ ADMIN VALIDASI ------======#
  get "/dashboards/admin", to: "admins#index"
  get "/dashboards/admin/permohonan", to: "admins#applications"
  get "/dashboards/admin/permohonan/session/set", to: "admins#submission_set"
  get "/dashboards/admin/permohonan/session/approve", to: "admins#submission_approve"
  delete "/dashboards/admin/permohonan/session/delete", to: "admins#submission_delete"
  get "/dashboards/admin/permohonan/loket", to: "admins#counter"
  get "/dashboards/admin/permohonan/loket/ambil/:id", to: "admins#taken_submission", as: "admin_taken_submission"
  post "/dashboards/admin/permohonan/loket/ambil/process", to: "admins#process_taken_submission", as: "admin_process_taken_submission"
  get "/dashboards/admin/permohonan/revisi", to: "admins#revisions"
  get "/dashboards/admin/permohonan/revisi/member/:id", to: "admins#member_revisions", as: "admin_member_revision"
  post "/dashboards/admin/permohonan/revisi/member/process", to: "admins#process_member_revision", as: "admin_process_member_revision"
  get "/dashboards/admin/permohonan/setujui/:id", to: "admins#accept_submission", as: "admin_accept_submission"
  post "/dashboards/admin/permohonan/setujui/process", to: "admins#process_accept_submission", as: "admin_process_accept_submission"
  get "/dashboards/admin/permohonan/detail/:id", to: "admins#detail_submission", as: "admin_detail_submission"
  delete "/dashboards/admin/permohonan/delete/:id", to: "admins#delete_submission", as: "admin_delete_submission"

  #======------ KASUBSI ------======#
  get "/dashboards/kasubsi", to: "kasubsis#index"
  get "/dashboards/kasubsi/accept/:id", to: "kasubsis#accept_submission", as: "kasubsi_accept_submission"
  get "/dashboards/kasubsi/permohonan", to: "kasubsis#application_report"
  get "/dashboards/kasubsi/permohonan/detail/:id", to: "kasubsis#submission_detail", as: "kasubsi_detail_submission"
  get "/dashboards/kasubsi/permohonan/session/approve", to: "kasubsis#submission_approve"

  #======------ ADMIN INTIP ------======#
  get "intip/admin", to: "intips#index"
  get "intip/admin/members", to: "intips#members"
  get "intip/admin/members/new", to: "intips#new_member"
  post "intip/admin/members/create", to: "intips#create_member"
  get "intip/admin/members/edit/:id", to: "intips#edit_member", as: "intip_admin_members_edit"
  get "intip/admin/members/detail/:id", to: "intips#detail_member", as: "intip_admin_members_detail"
  delete "intip/admin/members/delete/:id", to: "intips#delete_member", as: "intip_admin_members_delete"
  put "intip/admin/members/edit/process/:id", to: "intips#process_edit_member", as: "intip_admin_members_edit_process"
  get "intip/admin/permohonan", to: "intips#submissions"
  get "intip/admin/intip/members", to: "intips#intip_members"
  get "intip/admin/intip/members/:id", to: "intips#intip_members_detail", as: "intip_admin_intip_members_detail"
  get "intip/admin/intip/members/:id/permohonan/:workspace_id", to: "intips#intip_members_permohonan", as: "intip_admin_intip_members_permohonan"

  #======------ GPS ADMIN ------======#
  get "gps/admin", to: "gps#index"
  get "gps/admin/gps/members", to: "gps#gps_members"
  get "gps/admin/gps/members/:id", to: "gps#gps_members_detail", as: "gps_admin_gps_members_detail"
  delete "gps/admin/gps/members/:id/delete/workspace/:workspace_id", to: "gps#delete_workspace_member", as: "gps_admin_gps_members_delete_workspace"
  get "gps/admin/gps/members/:id/permohonan/:workspace_id", to: "gps#gps_members_permohonan", as: "gps_admin_gps_members_permohonan"

  get "gps/admin/permohonan/:id", to: "gps#detail", as: "gps_admin_permohonan_detail"

  get "gps/admin/members", to: "gps#members"
  get "gps/admin/members/new", to: "gps#new_member"
  post "gps/admin/members/create", to: "gps#create_member"
  get "gps/admin/members/edit/:id", to: "gps#edit_member", as: "gps_admin_members_edit"
  get "gps/admin/members/detail/:id", to: "gps#detail_member", as: "gps_admin_members_detail"
  delete "gps/admin/members/delete/:id", to: "gps#delete_member", as: "gps_admin_members_delete"
  put "gps/admin/members/edit/process/:id", to: "gps#process_edit_member", as: "gps_admin_members_edit_process"

  #======------ MEMBER INTIP ------======#
  get "intip/member", to: "member_intips#index"
  get "intip/member/permohonan", to: "member_intips#intip"
  get "intip/member/permohonan/detail/:id", to: "member_intips#show", as: "intips_member_permohonan_detail"
  post "intip/member/permohonan/action", to: "member_intips#action"
  get "intip/member/permohonan/new", to: "member_intips#new_intip_submission"
  get "intip/member/permohonan/download", to: "member_intips#intip_submission"
  post "intip/member/permohonan/submit", to: "member_intips#submit_intip_submission"
  post "intip/member/permohonan/process-data", to: "member_intips#process_data"
  get "intips/workspaces", to: "intip_workspaces#index"
  post "intips/workspaces", to: "intip_workspaces#process_create"
  get "intips/workspaces/create", to: "intip_workspaces#create"
  get "intips/workspaces/detail/:id", to: "intip_workspaces#detail", as: "intips_member_workspaces_detail"
  delete "intips/workspaces/delete/:id", to: "intip_workspaces#delete", as: "intips_member_workspaces_delete"
  get "intips/workspaces/:id", to: "intip_workspaces#show", as: "intips_member_workspaces_show"
  get "intips/workspaces/:id/buat-permohonan", to: "intip_workspaces#new_submission", as: "intips_member_workspaces_new_submission"
  post "intips/workspaces/:id/buat-permohonan/process", to: "intip_workspaces#process_new_submission", as: "intips_member_workspaces_process_new_submission"
  post "intips/workspaces/permohonan/process-data", to: "intip_workspaces#process_data", as: "intips_member_workspaces_permohonan_process_data"

  #======------ GPS MEMBER ------======#
  get "gps/member", to: "member_gps#index"
  get "gps/member/permohonan", to: "member_gps#gps"
  get "gps/member/permohonan/new", to: "member_gps#new_gps_submission"
  post "gps/member/permohonan/submit", to: "member_gps#submit_gps_submission"
  delete "gps/member/permohonan/delete", to: "member_gps#delete_gps_submission"
  put "gps/member/permohonan/sent", to: "member_gps#sent_gps_submission"
  get "gps/member/permohonan/:id", to: "member_gps#detail_gps_submission", as: "gps_member_permohonan_detail"
  get "gps/member/permohonan/edit/:id", to: "member_gps#edit_gps_submission", as: "gps_member_permohonan_edit"

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def counter; end

  def profile
    @user = current_user
    @notifications = current_user.my_notifications
  end

  def update_profile
    current_user.update(user_params)
    current_user.user_detail.update(user_details_params)
    flash[:notice] = 'Berhasil memperbaharui data profil.'
    redirect_to dashboards_profile_path
  end

  def update_password
    valid = current_user.valid_password?(password_params['current_password'])
    if valid && (password_params['new_password'].length >= 6) && (password_params['new_password'] == password_params['confirmation_password'])
      current_user.update(password: password_params['new_password'])
      sign_in(current_user, bypass: true)
      flash[:notice] = 'Berhasil memperbaharui password.'
      redirect_to dashboards_profile_path
    else
      flash[:errors] = ['Password baru yang anda masukkan tidak valid.']
      redirect_to dashboards_profile_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end

  def user_details_params
    params.require(:user).permit(
      :address,
      :fullname,
      :username,
      :id_number,
      :phone_number
    )
  end

  def password_params
    params.require(:pass).permit(
      :new_password,
      :current_password,
      :confirmation_password
    )
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/sidebar_navigation/_admin_gps_nav.html.erb
<nav class="flex-1 px-2 py-4 bg-gray-800 space-y-1">

    <%= link_to gps_admin_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-white rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/gps/admin') }", role: "menuitem" do %>
      <!-- Heroicon name: home -->
      <svg class="mr-3 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
      Dashboard
    <% end %>

    <%= link_to gps_admin_members_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/gps/admin/members') }", role: "menuitem" do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
      Member
    <% end %>

    <%= link_to gps_admin_gps_members_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/gps/admin/permohonan') }", role: "menuitem" do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2" />
      </svg>
      Gerakan Plotting Serentak
    <% end %>

    <%= link_to destroy_user_session_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700", role: "menuitem", :method => :delete do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
      </svg>
      Keluar
    <% end %>

</nav>

app/views/dashboards/sidebar_navigation/_admin_nav.html.erb
<nav class="flex-1 px-2 py-4 bg-gray-800 space-y-1">

    <%= link_to dashboards_admin_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-white rounded-md #{ is_active?('/dashboards/admin') }", role: "menuitem" do %>
      <!-- Heroicon name: home -->
      <svg class="mr-3 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
      Dashboard
    <% end %>

    <%= link_to dashboards_admin_permohonan_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/dashboards/admin/permohonan') }", role: "menuitem" do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2" />
      </svg>
      Semua Permohonan
    <% end %>

    <%= link_to dashboards_admin_permohonan_revisi_path,method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/dashboards/admin/permohonan/revisi') }", role: "menuitem" do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Revisi
    <% end %>

    <%= link_to dashboards_admin_permohonan_loket_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/dashboards/admin/permohonan/loket') }", role: "menuitem" do %>
      <!-- Heroicon name: inbox -->
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
      </svg>
      Selesai
    <% end %>

    <%= link_to destroy_user_session_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700", role: "menuitem", :method => :delete do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
      </svg>
      Keluar
    <% end %>

</nav>

app/views/dashboards/sidebar_navigation/_super_admin_nav.html.erb
<nav class="flex-1 px-2 py-4 bg-gray-800 space-y-1">

    <%= link_to superadmin_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-white rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/superadmin') }", role: "menuitem" do %>
      <!-- Heroicon name: home -->
      <svg class="mr-3 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
      Dashboard
    <% end %>

    <%= link_to superadmin_validasi_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/superadmin/validasi') }", role: "menuitem" do %>
      <!-- Heroicon name: calendar -->
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      Validasi
    <% end %>

    <%= link_to superadmin_pola_ruang_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/superadmin/pola-ruang') }", role: "menuitem" do %>
      <!-- Heroicon name: calendar -->
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      Pola Ruang
    <% end %>

    <%= link_to superadmin_admin_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/superadmin/admin') }", role: "menuitem" do %>
      <!-- Heroicon name: calendar -->
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      Admin / Kasubsi
    <% end %>

    <%= link_to superadmin_member_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/superadmin/member') }", role: "menuitem" do %>
      <!-- Heroicon name: inbox -->
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
      </svg>
    Member
    <% end %>

    <%= link_to superadmin_settings_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700 #{ is_active?('/superadmin/settings') }", role: "menuitem" do %>
      <!-- Heroicon name: inbox -->
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
      </svg>
    Setting
    <% end %>

    <%= link_to destroy_user_session_path, method: 'get', class: "group flex items-center px-2 py-2 text-sm font-medium text-gray-300 rounded-md hover:text-white hover:bg-gray-700", role: "menuitem", :method => :delete do %>
      <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
      </svg>
      Keluar
    <% end %>
</nav>