config/routes.rb
Rails.application.routes.draw do
  get "intip_workspaces/index"
  get "workspaces/index"

  # devise routes
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  # rails admin routes
  mount RailsAdmin::Engine => "/secretroom", as: "rails_admin"

  root "homepages#index"
  get "privacy-policy", to: "homepages#privacy_policy"
  get "carts", to: "carts#index"
  get "/hello", to: "homepages#hello"
  get "/pdf", to: "homepages#generatepdf"
  get "/table-data/session/set", to: "application#submission_set"

  #======------ SETTINGS ------======#
  post "/settings/update", to: "super_admins#update_settings"

  #======------ DASHBOARDS ------======#
  get "/dashboards", to: "dashboards#index"
  get "/dashboards/counter", to: "dashboards#counter"
  get "/dashboards/profile", to: "dashboards#profile"
  post "/dashboards/profile/update", to: "dashboards#update_profile"
  post "/dashboards/password/update", to: "dashboards#update_password"

  #======------ SUPER ADMIN ------======#
  get "/superadmin", to: "super_admins#index"
  get "/superadmin/member", to: "super_admins#list_member"
  get "/superadmin/member/edit/:id", to: "super_admins#edit_member", as: "sa_edit_member"
  post "/superadmin/member/edit/process", to: "super_admins#process_update_member"
  get "/superadmin/member/new", to: "super_admins#new_member", as: "sa_new_member"
  post "/superadmin/member/new/process", to: "super_admins#process_create_member"
  delete "/superadmin/member/delete/all", to: "super_admins#destroy_all_member", as: "sa_destroy_all_member"
  delete "/superadmin/member/delete/:id", to: "super_admins#destroy_member", as: "sa_destroy_member"
  get "/superadmin/admin", to: "super_admins#list_admin"
  get "/superadmin/admin/edit/:id", to: "super_admins#edit_admin", as: "sa_edit_admin"
  post "/superadmin/admin/edit/process", to: "super_admins#process_update_admin"
  get "/superadmin/admin/new", to: "super_admins#new_admin", as: "sa_new_admin"
  post "/superadmin/admin/new/process", to: "super_admins#process_create_admin"
  delete "/superadmin/admin/delete/:id", to: "super_admins#destroy_admin", as: "sa_destroy_admin"
  get "/superadmin/validasi", to: "super_admins#validations"
  get "/superadmin/validasi/:id", to: "super_admins#validation_detail", as: "sa_validation_detail"
  get "/superadmin/pola-ruang", to: "super_admins#space_patterns"
  get "/superadmin/pola-ruang/:id", to: "super_admins#space_pattern_detail", as: "sa_space_pattern_detail"
  get "/superadmin/settings", to: "super_admins#settings"

  #======------ MEMBER VALIDASI ------======#
  get "/dashboards/member", to: "members#index"
  get "/dashboards/member/validasi", to: "members#validation"
  get "/dashboards/member/validasi/submission", to: "members#validation_submission"
  post "/dashboards/member/validasi/submission", to: "members#validation_process_submission"
  get "/dashboards/member/pola-ruang", to: "members#space_pattern"
  get "/dashboards/member/pola-ruang/submission", to: "members#space_pattern_submission"
  post "/dashboards/member/pola-ruang/submission", to: "members#space_pattern_process_submission"
  get "/dashboards/member/submission/edit/:id", to: "members#submission_edit", as: "member_submission_edit"
  get "/dashboards/member/submission/detail/:id", to: "members#submission_detail", as: "member_submission_detail"
  put "/dashboards/member/submission/detail/:id", to: "members#prosess_submission_edit", as: "member_process_submission_edit"

  #======------ ADMIN VALIDASI ------======#
  get "/dashboards/admin", to: "admins#index"
  get "/dashboards/admin/permohonan", to: "admins#applications"
  get "/dashboards/admin/permohonan/session/set", to: "admins#submission_set"
  get "/dashboards/admin/permohonan/session/approve", to: "admins#submission_approve"
  delete "/dashboards/admin/permohonan/session/delete", to: "admins#submission_delete"
  get "/dashboards/admin/permohonan/loket", to: "admins#counter"
  get "/dashboards/admin/permohonan/loket/ambil/:id", to: "admins#taken_submission", as: "admin_taken_submission"
  post "/dashboards/admin/permohonan/loket/ambil/process", to: "admins#process_taken_submission", as: "admin_process_taken_submission"
  get "/dashboards/admin/permohonan/revisi", to: "admins#revisions"
  get "/dashboards/admin/permohonan/revisi/member/:id", to: "admins#member_revisions", as: "admin_member_revision"
  post "/dashboards/admin/permohonan/revisi/member/process", to: "admins#process_member_revision", as: "admin_process_member_revision"
  get "/dashboards/admin/permohonan/setujui/:id", to: "admins#accept_submission", as: "admin_accept_submission"
  post "/dashboards/admin/permohonan/setujui/process", to: "admins#process_accept_submission", as: "admin_process_accept_submission"
  get "/dashboards/admin/permohonan/detail/:id", to: "admins#detail_submission", as: "admin_detail_submission"
  delete "/dashboards/admin/permohonan/delete/:id", to: "admins#delete_submission", as: "admin_delete_submission"

  #======------ KASUBSI ------======#
  get "/dashboards/kasubsi", to: "kasubsis#index"
  get "/dashboards/kasubsi/accept/:id", to: "kasubsis#accept_submission", as: "kasubsi_accept_submission"
  get "/dashboards/kasubsi/permohonan", to: "kasubsis#application_report"
  get "/dashboards/kasubsi/permohonan/detail/:id", to: "kasubsis#submission_detail", as: "kasubsi_detail_submission"
  get "/dashboards/kasubsi/permohonan/session/approve", to: "kasubsis#submission_approve"

  #======------ ADMIN INTIP ------======#
  get "intip/admin", to: "intips#index"
  get "intip/admin/members", to: "intips#members"
  get "intip/admin/members/new", to: "intips#new_member"
  post "intip/admin/members/create", to: "intips#create_member"
  get "intip/admin/members/edit/:id", to: "intips#edit_member", as: "intip_admin_members_edit"
  get "intip/admin/members/detail/:id", to: "intips#detail_member", as: "intip_admin_members_detail"
  delete "intip/admin/members/delete/:id", to: "intips#delete_member", as: "intip_admin_members_delete"
  put "intip/admin/members/edit/process/:id", to: "intips#process_edit_member", as: "intip_admin_members_edit_process"
  get "intip/admin/permohonan", to: "intips#submissions"
  get "intip/admin/intip/members", to: "intips#intip_members"
  get "intip/admin/intip/members/:id", to: "intips#intip_members_detail", as: "intip_admin_intip_members_detail"
  get "intip/admin/intip/members/:id/permohonan/:workspace_id", to: "intips#intip_members_permohonan", as: "intip_admin_intip_members_permohonan"

  #======------ GPS ADMIN ------======#
  get "gps/admin", to: "gps#index"
  get "gps/admin/gps/members", to: "gps#gps_members"
  get "gps/admin/gps/members/:id", to: "gps#gps_members_detail", as: "gps_admin_gps_members_detail"
  delete "gps/admin/gps/members/:id/delete/workspace/:workspace_id", to: "gps#delete_workspace_member", as: "gps_admin_gps_members_delete_workspace"
  get "gps/admin/gps/members/:id/permohonan/:workspace_id", to: "gps#gps_members_permohonan", as: "gps_admin_gps_members_permohonan"

  get "gps/admin/permohonan/:id", to: "gps#detail", as: "gps_admin_permohonan_detail"

  get "gps/admin/members", to: "gps#members"
  get "gps/admin/members/new", to: "gps#new_member"
  post "gps/admin/members/create", to: "gps#create_member"
  get "gps/admin/members/edit/:id", to: "gps#edit_member", as: "gps_admin_members_edit"
  get "gps/admin/members/detail/:id", to: "gps#detail_member", as: "gps_admin_members_detail"
  delete "gps/admin/members/delete/:id", to: "gps#delete_member", as: "gps_admin_members_delete"
  put "gps/admin/members/edit/process/:id", to: "gps#process_edit_member", as: "gps_admin_members_edit_process"

  #======------ MEMBER INTIP ------======#
  get "intip/member", to: "member_intips#index"
  get "intip/member/permohonan", to: "member_intips#intip"
  get "intip/member/permohonan/detail/:id", to: "member_intips#show", as: "intips_member_permohonan_detail"
  post "intip/member/permohonan/action", to: "member_intips#action"
  get "intip/member/permohonan/new", to: "member_intips#new_intip_submission"
  get "intip/member/permohonan/download", to: "member_intips#intip_submission"
  post "intip/member/permohonan/submit", to: "member_intips#submit_intip_submission"
  post "intip/member/permohonan/process-data", to: "member_intips#process_data"
  get "intips/workspaces", to: "intip_workspaces#index"
  post "intips/workspaces", to: "intip_workspaces#process_create"
  get "intips/workspaces/create", to: "intip_workspaces#create"
  get "intips/workspaces/detail/:id", to: "intip_workspaces#detail", as: "intips_member_workspaces_detail"
  delete "intips/workspaces/delete/:id", to: "intip_workspaces#delete", as: "intips_member_workspaces_delete"
  get "intips/workspaces/:id", to: "intip_workspaces#show", as: "intips_member_workspaces_show"
  get "intips/workspaces/:id/buat-permohonan", to: "intip_workspaces#new_submission", as: "intips_member_workspaces_new_submission"
  post "intips/workspaces/:id/buat-permohonan/process", to: "intip_workspaces#process_new_submission", as: "intips_member_workspaces_process_new_submission"
  post "intips/workspaces/permohonan/process-data", to: "intip_workspaces#process_data", as: "intips_member_workspaces_permohonan_process_data"

  #======------ GPS MEMBER ------======#
  get "gps/member", to: "member_gps#index"
  get "gps/member/permohonan", to: "member_gps#gps"
  get "gps/member/permohonan/new", to: "member_gps#new_gps_submission"
  post "gps/member/permohonan/submit", to: "member_gps#submit_gps_submission"
  delete "gps/member/permohonan/delete", to: "member_gps#delete_gps_submission"
  put "gps/member/permohonan/sent", to: "member_gps#sent_gps_submission"
  get "gps/member/permohonan/:id", to: "member_gps#detail_gps_submission", as: "gps_member_permohonan_detail"
  get "gps/member/permohonan/edit/:id", to: "member_gps#edit_gps_submission", as: "gps_member_permohonan_edit"

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipients, foreign_key: 'recipient_id', class_name: 'Notification'
  has_many :actors, foreign_key: 'actor_id', class_name: 'Notification'
  has_many :notifications, foreign_key: :recipient_id
  has_one :user_detail, dependent: :destroy
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :submissions, dependent: :destroy
  has_many :intips, dependent: :destroy
  has_many :gps_plottings, dependent: :destroy
  has_many :workspaces, dependent: :destroy
  has_many :working_areas, dependent: :destroy

  validates :username, uniqueness: true
  validates :email, uniqueness: true

  scope :members, -> { joins(:roles).where('roles.name ILIKE ?', '%member%') }
  scope :admins, -> { joins(:roles).where('roles.name ILIKE ? OR roles.name ILIKE ?', '%admin%', '%kasubsi%') }

  after_create :set_working_area_user

  # kaminari
  paginates_per 10

  def gps_with_workspace(workspace_id)
    return gps_plottings.where('sent_at IS NULL') unless workspace_id

    gps_plottings.where('sent_at IS NULL AND workspace_id = ?', workspace_id)
  end

  def set_working_area_user
    area = Area.find_by(is_default: true)
    WorkingArea.create(user_id: self.id, area_id: area.id)
  rescue
    Rails.logger.info '======> ERROR SET WORKING AREA <======'
  end

  def intips_today
    intips.where(created_at: Date.today)
  end

  def gps_plottings_today
    gps_plottings.where(created_at: Date.today)
  end

  def self.process_api_login(user)
    current_user = find_by(username: user['username'].to_s.downcase)
    auth         = current_user.present? && current_user.valid_password?(user['password'])
    confirmed    = current_user.confirmed_at.present? rescue false

    return { status: 'FAILED', errors: ['Failed to login'] } unless (current_user.present? && auth )
    return { status: 'FAILED', errors: ['You have to confirm your email address before continuing.'] } unless confirmed

    area = current_user.working_areas.first.area rescue nil
    token = get_auth_token(current_user.id)
    unless area.nil?
      { status: 'SUCCESS', results: { token: "Bearer #{token}", working_area_name: area.name, working_area_id: area.area_id } }
    else
      { status: 'SUCCESS', results: { token: "Bearer #{token}", working_area_name: '', working_area_id: '' } }
    end
  end

  def self.process_api_register(user)
    new_user = new(username: user['username'], password: user['password'], email: user['email'])
    return { status: 'FAILED', errors: new_user.errors.full_messages } unless new_user.save

    
    UserDetail.create(fullname: user['fullname'], id_number: user['id_number'], user_id: new_user.id)
    UserRole.find_or_create_by(user_id: new_user.id, role_id: Role.member_sipilot_id) # set default user register has member role

    { status: 'SUCCESS', results: { message: 'You will receive an email with instructions for how to confirm your email address in a few minutes.' } }
  end

  def self.get_auth_token(user_id)
    Auth.issue({ user: user_id })
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def my_notifications
    Notification.where('recipient_id = ? AND read_at IS NULL', id).order('created_at desc').uniq { |val| val.notifiable_id }
  end

  def self.member_intip
    joins(:user_roles, :roles).where('roles.name ILIKE ?', "%member intip%")
  end

  def self.member_gps
    joins(:user_roles, :roles).where('roles.name ILIKE ?', "%member gps%")
  end

  def member_sipilot_id
    Role.where('name ILIKE ?', "%member sipilot%").first.try(:id)
  end

  def admin_validasi?
    roles.where('name ILIKE ?', '%admin validasi%').present?
  end

  def admin_tematik?
    roles.where('name ILIKE ?', '%admin tematik%').present?
  end

  def admin_buku_tanah?
    roles.where('name ILIKE ?', '%admin buku tanah%').present?
  end

  def admin_pola_ruang?
    roles.where('name ILIKE ?', '%admin pola ruang%').present?
  end

  def member_sipilot?
    roles.where('name ILIKE ?', '%member sipilot%').present?
  end

  def admin_intip?
    roles.where('name ILIKE ?', '%admin intip%').present?
  end

  def member_intip?
    roles.where('name ILIKE ?', '%member intip%').present?
  end

  def admin_gps?
    roles.where('name ILIKE ?', '%admin gps%').present?
  end

  def member_gps?
    roles.where('name ILIKE ?', '%member gps%').present?
  end

  def kasubsi_tematik?
    roles.where('name ILIKE ?', '%kasubsi tematik%').present?
  end

  def kasubsi_pola_ruang?
    roles.where('name ILIKE ?', '%kasubsi pola ruang%').present?
  end

  def kasubsi_pendaftaran?
    roles.where('name ILIKE ?', '%kasubsi pendaftaran%').present?
  end

  def super_admin?
    roles.where('name ILIKE ?', '%super admin%').present?
  end

  def role_name
    roles.first.name
  rescue StandardError
    ''
  end

  def role_id
    roles.first.id
  rescue StandardError
    ''
  end

  def fullname
    user_detail&.fullname
  end

  def id_number
    user_detail&.id_number
  end

  def address
    user_detail&.address
  end

  def phone_number
    user_detail&.phone_number
  end

  def profile_photo
    # Rails.application.routes.url_helpers.rails_blob_url(user_detail.profile_photo, only_path: true)
    user_detail.profile_photo
  rescue StandardError
    ''
  end
end

app/helpers/intip_workspaces_helper.rb
module IntipWorkspacesHelper
end

app/views/intip_workspaces/_pagination.html.erb
<div class="bg-white px-4 py-3 flex items-center justify-between sm:px-6">
<div>
<%= page_entries_info @results , entry_name: name %>
</div>
    <div>
    <%= paginate @results %>
    </div>
</div>

app/views/intip_workspaces/_table_filter.html.erb
<%= search_form_for(@search, url: intips_member_workspaces_show_path, method: 'get') do |f| %>
  <div class="py-3 px-4 flex flex-wrap overflow-hidden bg-white border-b border-gray-200 ">
    <div class="my-2 px-2 w-full overflow-hidden sm:w-1/5 md:w-full lg:w-1/2 xl:w-1/2">
      <div>
          <%= f.label :created_at_gteq , "Date From", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 relative rounded-md shadow-sm">
          <%= f.date_field :created_at_gteq, value: @gteq_params, class: "block w-full pr-10 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-md" %>
          <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
            <svg class="h-5 w-5 text-blue-500"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
        </div>
      </div>
    </div>

    <div class="my-2 px-2 w-full overflow-hidden sm:w-1/5 md:w-full lg:w-1/2 xl:w-1/2">
      <div>
        <%= f.label :created_at_lteq , "Date To", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 relative rounded-md shadow-sm">
          <%= f.date_field :created_at_lteq, value: @lteq_params, class: "block w-full pr-10 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-md" %>
          <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
            <svg class="h-5 w-5 text-blue-500"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
        </div>
      </div>
    </div>

    <div class="my-2 px-2 w-full overflow-hidden sm:w-1/5 md:w-full lg:w-1/2 xl:w-1/2">
      <div class="mt-1">
        <%= f.submit "Search", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>
    </div>

  </div>
<% end %>

app/views/intip_workspaces/detail.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg my-4">

  <div class="bg-white px-4 py-5 sm:px-6">
    <div class="-ml-4 -mt-4 flex justify-between items-center flex-wrap sm:flex-nowrap">
      <div class="ml-4 mt-4">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Detail Workspace
        </h3>
      </div>
      <div class="ml-4 mt-4 flex-shrink-0">
        <%= link_to 'Kembali', :back, class: "relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>
    </div>
  </div>

  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Nama
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @workspace.name %>
        </dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          RT
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @workspace.rt %>
        </dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          RW
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @workspace.rw %>
        </dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Kabupaten
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @workspace.district.name %>
        </dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Kecamatan
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @workspace.sub_district.name %>
        </dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Desa
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" data-target='workspaceDetail.fullname'>
          <%= @workspace.village.name %>
        </dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Dari Tanggal
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" data-target='workspaceDetail.fullname'>
          <%= Formatter.date_dmy(@workspace.date_from) %>
        </dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Sampai Tanggal
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" data-target='workspaceDetail.fullname'>
          <%= Formatter.date_dmy(@workspace.date_to) %>
        </dd>
      </div>

    </dl>
  </div>
</div>

app/views/intip_workspaces/index.html.erb
<%= render 'shareds/table_title', name: 'Workspaces' %>

<div class="p-4 bg-white border-b border-gray-200 sm:flex sm:items-center sm:justify-between ">
  <div class="mt-3 flex sm:mt-0 sm:ml-4">
  <%= search_form_for(@search, url: intips_workspaces_path, method: 'get') do |f| %>
    <div>
    <div class="mt-1 flex rounded-md shadow-sm">
        <div class="relative flex items-stretch flex-grow focus-within:z-10">
        <%= f.text_field :name_cont, value: @last_query, class: "focus:ring-blue-500 focus:border-blue-500 block w-full rounded-none rounded-l-md sm:text-sm border-gray-300", placeholder: 'Search with name' %>
        </div>
        <%= f.submit class: "-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500" do %>
        <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
        <% end %>
    </div>
    </div>
<% end %>
  </div>

  <div class="mt-3 flex sm:mt-0 sm:ml-4">
    <%= link_to intips_workspaces_create_path, method: 'get', class: "ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" do %>
      <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
      </svg>
      Buat Workspaces
    <% end %>
  </div>
</div>

<div class="flex flex-col py-5">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                No
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Nama
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Total Data
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Aksi
              </th>
            </tr>
          </thead>
          <tbody>
            <!-- Odd row -->
            <% @results.each.with_index(1) do |workspace, index| %>
              <tr class="bg-white">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    <%= index %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  <%= link_to intips_member_workspaces_show_path(workspace) do %>
                    <%= workspace.name %>
                  <% end %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <%= workspace.intips.count %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= render 'shareds/tables/button_detail', action_path: intips_member_workspaces_detail_path(workspace) %>
                  <%= render 'shareds/tables/button_delete', action_path: intips_member_workspaces_delete_path(workspace) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render "shareds/pagination", data: @results, name: 'data' %>